### ISSUE TITLE
Base Autonumber prefix on Opportunity ID

### ISSUE THREAD

**Issue by ColleyV12** [rappen/AutoNumManager#22]
I it possible to populate part of the autonumber as the opportunity that generated an order, then reset the seed of the orders for the next opportunity

OPP0001 - 001
OPP0001 - 002

OPP0002 - 001

**Comment by rappen** [comment]
Unfortunately the platform functionality for Auto Numbers does not support this.
I would suggest looking at North52 or similar 3rd party solutions for such features.

**Comment by rappen** [comment]
To clairfy - It is the resetting seed that cannot be done OOB. Adding some intelligent code / low-code to combine a number field from opportunitynumber with autonumber on the order entity. And then a plugin identifying new order numbers, resetting the seed using the SDK. But I would not recommend such a solution because of the complexity and unambiguity that may be introduced if new orders are created to old opportunities etc.

**Comment by rappen** [comment]
Tip: https://jonasr.app/anm-unique-seq/

Please reopen if we need to do more.
