### ISSUE TITLE
Please document "Don't require SEQNUM" option

### ISSUE THREAD

**Issue by james-reinhardt** [rappen/AutoNumManager#24]
Under the attributes there is a field marked "Advanced 'Don't require SEQNUM'". This appears to have been added in a later version than the one the screenshots were taken in.

**Comment by rappen** [comment]
Most likely!
Which screenshot are you referring to?

**Comment by james-reinhardt** [comment]
The ones here http://anm.xrmtoolbox.com/
Thanks for the quick response. Can you give me a quick summary of what that option does?

**Comment by rappen** [comment]
I will have a look at the webpage 👍
If this checkbox is *not* checked, you are required to have a `{SEQNUM:n}` block in the format to ensure unique values.
But sometimes you might want to only use a random value or date based value, to do so you have to check this box to acknowledge that you are aware the resulting "numbers" may not always be unique.
A side effect is that to remove auto number format entirely from an attribute, this box must be checked since an empty number format does not contain `{SEQNUM:n}`...
